title: Jin Meng
logo: /assets/me.jpg
description: Visionary technical leader with track record of inspiring excellence and enhancing operational efficiency. Expert domain knowledge of analytics, data engineering, AI and data science. Innovative strategist with excellent analytical and technical acumen.  

show_downloads: true
theme: jekyll-theme-minimal
