title: Jin Meng
logo: /assets/me.png

description: Visionary technical leader with track record of inspiring excellence and enhancing operational efficiency.  

author:
  linkedin: "https://www.linkedin.com/in/jin-meng-29830673/"

show_downloads: true
theme: jekyll-theme-minimal
