title: Jin Meng
logo: /assets/me.png

description: Visionary technical leader with track record of inspiring excellence and enhancing operational efficiency.  

show_downloads: true
theme: jekyll-theme-minimal
